name: Cypress Tests

on: [push]

name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm run test:e2e:test